{
 "title": "Nomad Telemetry",
 "description": "Nomad built-in telemetry",
 "tags": [ "nomad" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "class", "query": "label_values(node)" },
   { "name": "instance", "query": "label_values(node)" },
   { "name": "job_type", "query": "label_values(job_type)" }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nomad Clients",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(nomad_client_allocated_disk)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Client Jobs",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(nomad_client_allocations_running, \"hostname\", \"$1\", \"instance\", \"(.*):.*\") ",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "nomad_nomad_job_summary_running",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  { "title": "Allocations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Running",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nomad_nomad_job_summary_running)"
    }
   ]
  },
  {
   "title": "Allocation Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "allocations" }
   ],
   "targets": [
    {
     "expr": "sum(nomad_client_allocations_blocked{instance=~\".+$class$instance.+\"})",
     "legendFormat": "blocked"
    },
    {
     "expr": "sum(nomad_client_allocations_migrating{instance=~\".+$class$instance.+\"})",
     "legendFormat": "migrating"
    },
    {
     "expr": "sum(nomad_client_allocations_pending{instance=~\".+$class$instance.+\"})",
     "legendFormat": "pending"
    },
    {
     "expr": "sum(nomad_client_allocations_running{instance=~\".+$class$instance.+\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum(nomad_client_allocations_terminal{instance=~\".+$class$instance.+\"})",
     "legendFormat": "terminal"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nomad_client_allocations_pending)"
    }
   ]
  },
  {
   "title": "Blocked",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nomad_client_allocations_blocked)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Allocation Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decmbytes", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "sum(nomad_client_allocs_memory_rss{instance=~\".+$class$instance.+\"} / 1024 / 1024)",
     "legendFormat": "utilization"
    },
    {
     "expr": "sum(nomad_client_allocated_memory{instance=~\".+$class$instance.+\"})",
     "legendFormat": "allocated"
    },
    {
     "expr": "sum(nomad_client_unallocated_memory{instance=~\".+$class$instance.+\"})",
     "legendFormat": "unallocated"
    }
   ]
  },
  {
   "title": "Host Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "decbytes", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "sum(nomad_client_host_memory_total{instance=~\".+$class$instance.+\"}) - sum(nomad_client_host_memory_available{instance=~\".+$class$instance.+\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(nomad_client_host_memory_available{instance=~\".+$class$instance.+\"})",
     "legendFormat": "available"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Allocation CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "hertz", "label": "allocated cpu Hz" }
   ],
   "targets": [
    {
     "expr": "sum(nomad_client_allocated_cpu{instance=~\".+$class$instance.+\"} * 1000 * 1000)",
     "legendFormat": "allocated"
    },
    {
     "expr": "sum(nomad_client_unallocated_cpu{instance=~\".+$class$instance.+\"} * 1000 * 1000)",
     "legendFormat": "unallocated"
    }
   ]
  },
  {
   "title": "Host CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "percent", "label": "host cpu" }
   ],
   "targets": [
    {
     "expr": "avg(nomad_client_host_cpu_system{instance=~\".+$class$instance.+\"})",
     "legendFormat": "system"
    },
    {
     "expr": "avg(nomad_client_host_cpu_user{instance=~\".+$class$instance.+\"})",
     "legendFormat": "user"
    },
    {
     "expr": "100 - (avg(nomad_client_host_cpu_user{instance=~\".+$class$instance.+\"}) + avg(nomad_client_host_cpu_system{instance=~\".+$class$instance.+\"}) + avg(nomad_client_host_cpu_idle{instance=~\".+$class$instance.+\"}))",
     "legendFormat": "other"
    },
    {
     "expr": "avg(nomad_client_host_cpu_idle{instance=~\".+$class$instance.+\"})",
     "legendFormat": "idle"
    },
    {
     "expr": "100 * (sum(nomad_client_allocated_cpu{instance=~\".+$class$instance.+\"} * 1000 * 1000) / (sum(nomad_client_allocated_cpu{instance=~\".+$class$instance.+\"} * 1000 * 1000) + sum(nomad_client_unallocated_cpu{instance=~\".+$class$instance.+\"} * 1000 * 1000)))",
     "legendFormat": "allocated"
    }
   ]
  },
  {
   "title": "Throttle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "throttle time" }
   ],
   "targets": [
    {
     "expr": "sum(nomad_client_allocs_cpu_throttled_time{instance=~\".+$class$instance.+\"})",
     "legendFormat": "throttled time sum"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Host Disk Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "percent", "label": "used disk" }
   ],
   "targets": [
    {
     "expr": "nomad_client_host_disk_used_percent{instance=~\".+$class$instance.+\"}",
     "legendFormat": "{{ instance }}  - {{ disk }}"
    }
   ]
  },
  {
   "title": "Host inode Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "percent", "label": "used inodes" }
   ],
   "targets": [
    {
     "expr": "nomad_client_host_disk_inodes_percent{instance=~\".+$class$instance.+\"}",
     "legendFormat": "{{ instance }}  - {{ disk }}"
    }
   ]
  }
 ]
}